### ISSUE TITLE
v0.1.0 Release

### ISSUE THREAD

**Issue by sywhang** [uber/mock#17]
We'll be tagging a v0.1.0 release with the current master branch, which does not have any additional features from the upstream golang/mock project (other than import path). This will serve as a base point before we put in more features to this. 

Following this we'll start reviewing community contributed PRs as well as address internal users' bug fix and feature requests.

**Comment by sywhang** [comment]
@linzhp and @r-hang: Let me know if you guys disagree with this. Otherwise I'll go ahead and tag a release.

**Comment by linzhp** [comment]
good idea

**Comment by r-hang** [comment]
sgtm!

**Comment by sywhang** [comment]
[v0.1.0](https://github.com/uber/mock/releases/tag/v0.1.0) has been released
