### ISSUE TITLE
`go get go.uber.org/mock` failure

### ISSUE THREAD

**Issue by bizywizy** [uber/mock#9]
**Actual behavior** 
```
❯ go get go.uber.org/mock                                                                                                                                                                                                    (cp-us-west-2/fetchers)
go: unrecognized import path "go.uber.org/mock": reading https://go.uber.org/mock?go-get=1: 404 Not Found
        server response: 404 page not found

```

**Expected behavior** 
Successful installation

**Additional Information**
`go version go1.20.4 darwin/arm64`

**Comment by sywhang** [comment]
Thanks for submitting this issue. We haven't published this package under the vanity import path yet due to some internal issues; we plan on doing that in the next 1-2 weeks of time. 

I'll update this issue when we fix that. Thanks

**Comment by sywhang** [comment]
v0.1.0 has ben released - you can install with the following command now:

```
go install go.uber.org/mock/mockgen@v0.1.0
```
